apiVersion: v1
kind: Pod
metadata:
  name: docker
  labels:
    run: docker
    role: devops
spec:
  containers:
  - name: docker
    env:
      - name: DOCKER_HOST
        value: tcp://localhost:2375
    image: docker:latest
    securityContext:
      privileged: true
    volumeMounts:
      - name: devops-pvc
        mountPath: /var/lib/docker
