# for ever namespace the agent needs permission to deploy
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mud-dev-deploy-bind
  namespace: mud-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deploy-role
subjects:
- kind: ServiceAccount
  name: devops-sa
  namespace: devops
