# for ever namespace the agent needs permission to deploy
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mud-dev-deploy-bind
  namespace: mud-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deploy-role
subjects:
- kind: ServiceAccount
  name: devops-sa
  namespace: devops
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mud-local-pv
  namespace: mud-dev
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /var/mud-local-vol
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
---