apiVersion: v1
kind: Namespace
metadata:
  name: mud-dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mud-local-pvc
  namespace: mud-dev
spec:
  resources:
    requests:
      storage: 10Mi
  storageClassName: local-storage
  accessModes:
  - ReadOnlyMany
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mud-deploy
  namespace: mud-dev
  labels:
    role: app
    app: mud
spec:
  replicas: 3
  selector:
    matchExpressions:
      - { key: app, operator: In, values: [mud] }
  template:
    metadata:
      labels:
        run: mud-server-exe
        app: mud
        role: app
    spec:
      containers:
      - name: mud-app
        image: registry-svc.devops.svc.cluster.local:5000/mud:latest
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: mud-vol
          mountPath: /var/lib/mud/data
          subPath: mud_data
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
      imagePullSecrets:
      - name: registry
      volumes:
      - name: mud-vol
        persistentVolumeClaim:
          claimName: mud-local-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mud-svc
  namespace: mud-dev
  labels:
    role: app
    app: mud
spec:
  type: NodePort
  selector:
    run: mud-server-exe
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
---