apiVersion: v1
kind: Namespace
metadata:
  name: gogogadget
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-range
  namespace: gogogadget
spec:
  limits:
  - type: Container
    default:
      cpu: 250m
    defaultRequest:
      cpu: 125m
  - type: Pod
    min:
     cpu: 50m
    max:
     cpu: 1000m
  - type: PersistentVolumeClaim
    max:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: gogogadget
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sleep", "999999"]

