apiVersion: v1
kind: Pod
metadata:
  name: secret-vol
spec:
  containers:
  - name: thepod
    image: alpine:latest
    command: ["/bin/sleep", "99999"]
    volumeMounts:
    - name: spy
      mountPath: /secrets
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: super-secret
          key: username
  volumes:
  - name: spy
    secret:
      secretName: super-secret