apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    layer: four
spec:
  replicas: 3
  selector:
    matchExpressions:
      - {key: layer, operator: In, values: [four] }
  template:
    metadata:
      labels:
        layer: four
    spec:
      containers:
      - name: bbox
        image: ealen/echo-server
---
kind: Service
apiVersion: v1
metadata:
  name: cluster-ip-svc
  labels:
    app: best-app
spec:
  # type: NodePort
  selector:
    layer: four
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80
