name: 'Git Submodules'
description: 'Pull Git submodules recursivily using git'
runs:
  using: "composite"
  steps:
    - run: |
        git submodule sync --recursive
        git submodule update --init --force  --recursive --depth=1
      shell: bash