name: BrickTrader App

on:
  workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v3

      - name: Checkout submodules
        uses: ./.github/actions/gitsubmodules

      - name: Build
        run: docker build -t bricktrader:latest -f repos/bricktrader/Dockerfile ./

      - name: Copy
        run: docker run --rm --entrypoint cat bricktrader:latest dist/bricktrader-exe > bricktrader-exe

      - uses: actions/upload-artifact@v2
        with:
          name: bricktrader
          path: bricktrader-exe
