name: Test dind in k8s

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: build mud
      run: docker build -t mud:tama -f repos/mud/server/Dockerfile --target runtime repos/mud/server
    
