name: Mud App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GIT_SSH_COMMAND: "ssh -i /etc/ssh_keys/ssh-github -o IdentitiesOnly=yes"

jobs:

  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Checkout submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --force  --recursive --depth=1

    - name: build mud with docker
      run: docker build -t mud:${{ github.run_id }} -f repos/mud/server/Dockerfile --target runtime repos/mud/server

    - name: tag image with our repository
      run: docker tag mud:${{ github.run_id }} registry-svc.default.svc.cluster.local:5000/mud:${{ github.run_id }}

    - name: push image to internal repo
      run: docker push registry-svc.default.svc.cluster.local:5000/mud:${{ github.run_id }}

    - name: rollout deployment
      run: kubectl set image deployment/mud-deploy mud-app=registry-svc.default.svc.cluster.local:5000/mud:${{ github.run_id }}
