name: Mud App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: build mud with docker
      run: docker build -t mud:tama -f repos/mud/server/Dockerfile --target runtime repos/mud/server
    
    - name: tag image with our repository
      run: docker tag mud:tama registry-svc.default.svc.cluster.local:5000/mud:tama

    - name: push image to internal repo
      run: docker push registry-svc.default.svc.cluster.local:5000/mud:tama
    
    - name: rollout deployment
      run: kubectl set image deployment/mud-deploy mud-app=registry-svc.default.svc.cluster.local:5000/mud:tama
