name: Mud App

on:
  workflow_dispatch

jobs:

  build:
    runs-on: self-hosted

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Checkout submodules
      uses: ./.github/actions/gitsubmodules

    - name: Set Environment Variables
      uses: ./.github/actions/setenvvars
      with:
        varFilePath: ./.github/variables/clustervars.env

    - name: build mud with docker
      run: docker build -t mud:${{ github.run_id }} -f repos/mud/server/Dockerfile --target runtime repos/mud/server

    - name: tag image with our repository
      run: docker tag mud:${{ github.run_id }} ${{ env.CLUSTER_URN }}/mud:latest

    - name: push image to internal repo
      run: docker push ${{ env.CLUSTER_URN }}/mud:latest

    - name: rollout deployment
      run: kubectl set image deployment/mud-deploy mud-app=${{ env.CLUSTER_URN }}/mud:latest -n mud-dev
